version: '3.3'
secrets:
  ovh_application_key:
    file: "./secrets/ovh_application_key.secret"
  ovh_application_secret:
    file: "./secrets/ovh_application_secret.secret"
  ovh_consumer_key:
    file: "./secrets/ovh_consumer_key.secret"
  basicauth_users:
    file: "./secrets/basicauth_users.secret"

services:
  traefik:
    image: traefik:v2.4
    container_name: traefik
    command:  
      - --providers.docker 
      - --providers.docker.network=traefik_web
      - --providers.file.filename=/rules.yml
      - --entrypoints.web.address=:80
      - --entrypoints.websecure.address=:443
      - --api
      - --certificatesresolvers.le.acme.email=${LETSENCRYPT_EMAIL}
      - --certificatesresolvers.le.acme.storage=letsencrypt/acme.json
      - --certificatesresolvers.le.acme.dnschallenge=true
      - --certificatesresolvers.le.acme.dnschallenge.provider=ovh
      - --metrics.prometheus=true
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./letsencrypt:/letsencrypt
      - ${PWD}/rules.yml:/rules.yml
    networks:
      - traefik_web
    labels:
      - "traefik.http.middlewares.redirect-to-https.redirectscheme.scheme=https"
      - "traefik.http.routers.redirs.rule=hostregexp(`{host:.+}`)"
      - "traefik.http.routers.redirs.entrypoints=web"
      - "traefik.http.routers.redirs.middlewares=redirect-to-https"
      # Dashboard
      - "traefik.http.routers.traefik.rule=Host(`traefik.int.bend.ovh`)"
      - "traefik.http.routers.traefik.service=api@internal"
      - "traefik.http.routers.traefik.middlewares=admin"
      - "traefik.http.routers.traefik.tls.certresolver=le"
      - "traefik.http.routers.traefik.entrypoints=websecure"
      - 'traefik.http.middlewares.admin.basicauth.usersfile=/run/secrets/basicauth_users'
    secrets:
      - "ovh_application_key"
      - "ovh_application_secret"
      - "ovh_consumer_key"
      - "basicauth_users"
    environment:
      - "OVH_ENDPOINT=ovh-eu"
      - "OVH_APPLICATION_KEY_FILE=/run/secrets/ovh_application_key"
      - "OVH_APPLICATION_SECRET_FILE=/run/secrets/ovh_application_secret"
      - "OVH_CONSUMER_KEY_FILE=/run/secrets/ovh_consumer_key"      
    restart: always
networks:
  traefik_web:
    external: true
